## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID       City Country  Max Temp   Current Description    Lat     Lng  \
0        0      Kapaa      US     77.00            light rain  22.08 -159.32   
1        2       Suba      PH     83.68            light rain  10.84  121.01   
2        3  Hithadhoo      MV     82.17  heavy intensity rain  -0.60   73.08   
3        7     Bosaso      SO     76.59             clear sky  11.28   49.18   
4        8  Namatanai      PG     83.75         broken clouds  -3.67  152.43   

  Hotel Name  
0     Kapaʻa  
1       Cuyo  
2  Addu City  
3     Bosaso  
4  Namatanai

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map. 
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [5]:
australia_vacation_df = vacation_df.loc[(vacation_df["Country"] == "AU")]
australia_vacation_df

City_ID            City Country  Max Temp Current Description    Lat  \
10        22          Hobart      AU     77.00           clear sky -42.88   
14        41     New Norfolk      AU     77.00     overcast clouds -42.78   
29       100       Esperance      AU     80.60          light rain -33.87   
40       149  Victoria Point      AU     79.00    scattered clouds -27.58   
47       175      Port Pirie      AU     87.80          few clouds -33.18   
69       270    Port Augusta      AU     86.00    scattered clouds -32.50   
71       282      Deniliquin      AU     81.52           clear sky -35.53   
85       333   Mount Gambier      AU     82.40    scattered clouds -37.83   
91       347    Port Lincoln      AU     77.79       broken clouds -34.73   
96       369   Victor Harbor      AU     78.01          few clouds -35.57   
142      557          Gympie      AU     79.95          few clouds -26.19   
151      581      Hervey Bay      AU     80.01           clear sky -25.30   
153      589         Yeppoon      AU     89.60       broken clouds -23.13   
154      591     Broken Hill      AU     82.40          few clouds -31.95   
166      620        Karratha      AU     82.20    scattered clouds -20.74   

        Lng              Hotel Name  
10   147.33                  Hobart  
14   147.06             New Norfolk  
29   121.90               Esperance  
40   153.30                Brisbane  
47   138.02              Port Pirie  
69   137.77            Port Augusta  
71   144.97              Deniliquin  
85   140.77           Mount Gambier  
91   135.87            Port Lincoln  
96   138.62  Victor Harbor - Goolwa  
142  152.66                  Gympie  
151  152.85              Hervey Bay  
153  150.73                 Yeppoon  
154  141.43             Broken Hill  
166  116.85                Karratha

In [6]:
australia_vacation_df.isnull().sum()

City_ID                0
City                   0
Country                0
Max Temp               0
Current Description    0
Lat                    0
Lng                    0
Hotel Name             0
dtype: int64

In [162]:
australia_vacation_df = australia_vacation_df.reset_index(drop=True)
australia_vacation_df

City_ID            City Country  Max Temp Current Description    Lat  \
0        22          Hobart      AU     77.00           clear sky -42.88   
1        41     New Norfolk      AU     77.00     overcast clouds -42.78   
2       100       Esperance      AU     80.60          light rain -33.87   
3       149  Victoria Point      AU     79.00    scattered clouds -27.58   
4       175      Port Pirie      AU     87.80          few clouds -33.18   
5       270    Port Augusta      AU     86.00    scattered clouds -32.50   
6       282      Deniliquin      AU     81.52           clear sky -35.53   
7       333   Mount Gambier      AU     82.40    scattered clouds -37.83   
8       347    Port Lincoln      AU     77.79       broken clouds -34.73   
9       369   Victor Harbor      AU     78.01          few clouds -35.57   
10      557          Gympie      AU     79.95          few clouds -26.19   
11      581      Hervey Bay      AU     80.01           clear sky -25.30   
12      589         Yeppoon      AU     89.60       broken clouds -23.13   
13      591     Broken Hill      AU     82.40          few clouds -31.95   
14      620        Karratha      AU     82.20    scattered clouds -20.74   

       Lng              Hotel Name  
0   147.33                  Hobart  
1   147.06             New Norfolk  
2   121.90               Esperance  
3   153.30                Brisbane  
4   138.02              Port Pirie  
5   137.77            Port Augusta  
6   144.97              Deniliquin  
7   140.77           Mount Gambier  
8   135.87            Port Lincoln  
9   138.62  Victor Harbor - Goolwa  
10  152.66                  Gympie  
11  152.85              Hervey Bay  
12  150.73                 Yeppoon  
13  141.43             Broken Hill  
14  116.85                Karratha

In [182]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = australia_vacation_df.loc[(australia_vacation_df['City_ID'] == 149)]
vacation_end = australia_vacation_df.loc[(australia_vacation_df['City_ID'] == 149)]
vacation_stop1 = australia_vacation_df.loc[(australia_vacation_df['City_ID'] == 557)]
vacation_stop2 = australia_vacation_df.loc[(australia_vacation_df['City_ID'] == 581)]
vacation_stop3 = australia_vacation_df.loc[(australia_vacation_df['City_ID'] == 589)] 

In [183]:
vacation_start

City_ID            City Country  Max Temp Current Description    Lat  \
3      149  Victoria Point      AU      79.0    scattered clouds -27.58   

     Lng Hotel Name  
3  153.3   Brisbane

In [184]:
vacation_end

City_ID            City Country  Max Temp Current Description    Lat  \
3      149  Victoria Point      AU      79.0    scattered clouds -27.58   

     Lng Hotel Name  
3  153.3   Brisbane

In [185]:
vacation_stop1

City_ID    City Country  Max Temp Current Description    Lat     Lng  \
10      557  Gympie      AU     79.95          few clouds -26.19  152.66   

   Hotel Name  
10     Gympie

In [24]:
vacation_stop2

City_ID        City Country  Max Temp Current Description   Lat     Lng  \
11      581  Hervey Bay      AU     80.01           clear sky -25.3  152.85   

    Hotel Name  
11  Hervey Bay

In [25]:
vacation_stop3

City_ID     City Country  Max Temp Current Description    Lat     Lng  \
12      589  Yeppoon      AU      89.6       broken clouds -23.13  150.73   

   Hotel Name  
12    Yeppoon

In [144]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[['Lat', 'Lng']].to_numpy()
end = vacation_end[['Lat', 'Lng']].to_numpy()
stop1 = vacation_stop1[['Lat', 'Lng']].to_numpy()
stop2 = vacation_stop2[['Lat', 'Lng']].to_numpy()
stop3 = vacation_stop3[['Lat', 'Lng']].to_numpy()

print(start)


[[-27.58 153.3 ]]


In [145]:
print(end)

[[-27.58 153.3 ]]


In [146]:
print(stop1)

[[-26.19 152.66]]


In [147]:
print(stop2)

[[-25.3  152.85]]


In [148]:
print(stop3)

[[-23.13 150.73]]


In [149]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps
import gmaps.datasets
gmaps.configure(api_key=g_key)

start = (-27.58, 153.3)
stop1 = (-26.19, 152.66)
stop2 = (-25.3, 152.85)
stop3 = (-23.13, 150.73)
end = (-27.58, 153.3)

fig = gmaps.figure()
start_end_with_stops = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')
fig.add_layer(start_end_with_stops)
fig

Figure(layout=FigureLayout(height='420px'))

In [176]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
australia_itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end], ignore_index=True)
australia_itinerary_df

City_ID            City Country  Max Temp Current Description    Lat  \
0      149  Victoria Point      AU     79.00    scattered clouds -27.58   
1      557          Gympie      AU     79.95          few clouds -26.19   
2      581      Hervey Bay      AU     80.01           clear sky -25.30   
3      589         Yeppoon      AU     89.60       broken clouds -23.13   
4      149  Victoria Point      AU     79.00    scattered clouds -27.58   

      Lng  Hotel Name  
0  153.30    Brisbane  
1  152.66      Gympie  
2  152.85  Hervey Bay  
3  150.73     Yeppoon  
4  153.30    Brisbane

In [188]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in australia_itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = australia_itinerary_df[["Lat", "Lng"]]

locations

Lat     Lng
0 -27.58  153.30
1 -26.19  152.66
2 -25.30  152.85
3 -23.13  150.73
4 -27.58  153.30

In [189]:
# 11a. Add a marker layer for each city to the map.
city_name = australia_itinerary_df["City"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))